### ISSUE TITLE
 Artifact Type "File Share" support

### ISSUE THREAD

**Issue by tomasspal** [BoolBySigma/FetchBuildArtifact#1]
Hello,

This plugin support only Artifact Type "Server". Is it possible also add support for Artifact Type "File Share" ? 
Hint: 
REST API 
.._apis/build/builds/<build ID>/artifacts?artifactName=<atrifact name>

return follow valuses:
in case "Server" .. "resource":{"type":"Container"...
in case "File Share" ..resource":{"type":"filepath", ...
and in "data": is path to folder which is just needed to copy to target folder

Thank you

Tomas

**Comment by ghost** [comment]
Published an update that supports both server and file share
