### ISSUE TITLE
Failed cp: No such file or directory

### ISSUE THREAD

**Issue by dtorg** [BoolBySigma/FetchBuildArtifact#4]
[logs_64587.zip](https://github.com/BoolBySigma/FetchBuildArtifact/files/922149/logs_64587.zip)

A new issue has arisen with the fetch operation. The artifact is named "drop" in my build and the software is looking for the folder ...\...\drop which in my build does not exist in my build. However I manually created the folder at that location and Fetch Artifact still cannot find the folder.

**Comment by ghost** [comment]
If InstrumentControlSDK_Aries10_Market1.Rel_2.1.942.0_B.1 publishes artifact 'drop' then the file share build folder should contain folder drop.

Could you try running a build that publishes drop and then fetch that build?

**Comment by dtorg** [comment]
[logs_64600.zip](https://github.com/BoolBySigma/FetchBuildArtifact/files/922293/logs_64600.zip)

It progressed a little further when I selected a different project. The previous project was one generated from a XAML build.

**Comment by ghost** [comment]
Added fix to account for differences between agent versions
