### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by dtorg** [BoolBySigma/FetchBuildArtifact#5]
[logs_64653.zip](https://github.com/BoolBySigma/FetchBuildArtifact/files/926381/logs_64653.zip)

One more issue. Operation not permitted getting the drop zip.

Thanks for all the help, hopefully the last. 

Dave

**Comment by ghost** [comment]
That looks like a permission error.

Are you running your build with the same account that ran the build that published drop?
Running agent with NT Authority\Network Service or other account?

**Comment by dtorg** [comment]
I fixed the service account and now it works. Unfortunately all my builds that I want to fetch are older XAML builds so I have to find another way to get those until I convert the builds. 

Thanks for your help.

**Comment by ghost** [comment]
Happy to help

Thanks for all your input
