### ISSUE TITLE
TFS2017: cannot find project <Guid>

### ISSUE THREAD

**Issue by martini1992** [BoolBySigma/FetchBuildArtifact#6]
When attempting to fetch an artifact in a TFS2017 build an error occurs because the project [Guid] cannot be found. Obviously replacing <Guid> with an actual guid. Maybe TFS2017 has changed the way it refers to projects? I have the OAuth option enabled and the correct project selected etc, but this error still occurs.

**Comment by ghost** [comment]
Thank you

Could you please run a build with variable system.debug set to true and upload the log?

Kind regards

**Comment by martini1992** [comment]
[3_Fetch Artifact Installer.txt](https://github.com/BoolBySigma/FetchBuildArtifact/files/964352/3_Fetch.Artifact.Installer.txt)

I've replaced names etc for security reasons

**Comment by ghost** [comment]
Thank you

I have published v 3.0.10 with additional error debugging for this area.

Could you please make sure you run v 3.0.10 and upload that log?

Kind regards

**Comment by martini1992** [comment]
[3_Fetch Artifact Installer More Debugging.txt](https://github.com/BoolBySigma/FetchBuildArtifact/files/964381/3_Fetch.Artifact.Installer.More.Debugging.txt)

Again edited for security

**Comment by ghost** [comment]
Thank you

Are you using a custom ssl certificate to access your tfs?

**Comment by martini1992** [comment]
Yes its a certificate signed against a custom root-ca certificate imported into the Windows certificate store.

Edit: Terminology

**Comment by ghost** [comment]
Ok. That is most likely the problem.

The task is only tested with vsts and tfs2017 without ssl cert.

I'll have a look at it and hopefully find a solution.

**Comment by martini1992** [comment]
Fair enough, and thank you :)

**Comment by ghost** [comment]
I have published v 3.0.11 with a patch for this issue.

Please try it out and let me know how it works for you.

**Comment by martini1992** [comment]
Excellent, thank you this has fixed the problem :)
