### ISSUE TITLE
feature request: download specific version of release artifacts

### ISSUE THREAD

**Issue by Geertvdc** [BoolBySigma/FetchBuildArtifact#7]
sometimes i just want to be able to use the artifacts of a specific release instead of the latest that exists. is it possible to add something like that to your task? would be great.

in VSTS this is already possible for your artifacts.

**Comment by ghost** [comment]
Hi. Thank you for your input.

It should be technically possible and I will look into it for possible future update.

**Comment by jdom** [comment]
👍 I would also like this feature very much
