### ISSUE TITLE
feature request: Clean Target Folder

### ISSUE THREAD

**Issue by ChrisRichner** [BoolBySigma/FetchBuildArtifact#8]
Hi there,

I'm successfully using your extension to download build artifacts. In our case we download the web app artifact to a web server while the integration test artifact is deployed to another machine.

Currently the integration test artifact gets unzipped into the Target Folder. The tests are run directly from the Target Folder. 

Each Test Run creates some result files which are published to VSTS. But Nobody deletes these files and the next Test Run publishes new and old files together.

I could add a new build step deleting the Target Folder myself. Wouldn't it  be nice to have such an Option inside your Extension?

What do you think?

**Comment by ghost** [comment]
Not sure if I have understood your requirement correctly but couldn't you use the built in clean function of the build definition and clean all build directories?

**Comment by ChrisRichner** [comment]
You're right. A Build Definition could do so. In my case I'm using a Release Definition which actually does not have a clean up feature.
